# Generated by Django 4.0.5 on 2022-06-29 08:32

from django.db import migrations, models
import loggma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('tr_id', models.IntegerField(default=0, validators=[loggma.models.validate_tr_id])),
                ('phone', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=200)),
                ('district', models.IntegerField(default=0)),
            ],
        ),
    ]
